version: "3.8"

services:
  cocos-frontend-treasure-hunter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80" # access at http://localhost:3000
    extra_hosts:
      - "host.docker.internal:host-gateway" # lets nginx reach your local backend
