// assets/scripts/core/GameEvents.ts
export enum GameEvent {
  // FSM State Transition Events
  BET_PLACED = "BET_PLACED",
  BET_CONFIRMED = "BET_CONFIRMED",
  BET_FAILED = "BET_FAILED",
  START_PRESSED = "START_PRESSED",
  JUMP_REQUESTED = "JUMP_REQUESTED",
  JUMP_RESULT_SAFE = "JUMP_RESULT_SAFE",
  JUMP_RESULT_TRAP = "JUMP_RESULT_TRAP",
  LANDING_COMPLETE = "LANDING_COMPLETE",
  CASHOUT_REQUESTED = "CASHOUT_REQUESTED",
  CASHOUT_COMPLETE = "CASHOUT_COMPLETE",
  ROUND_ENDED = "ROUND_ENDED",
  ROUND_ERROR = "ROUND_ERROR",
  NETWORK_ERROR = "NETWORK_ERROR",

  // API Events
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",
  BETS = "BETS",
  BETS_SELF = "BETS_SELF",
  WALLET_BALANCE_FETCHED = "WALLET_BALANCE_FETCHED",

  // Error / Notification Events
  SHOW_ERROR_NOTIFICATION = "SHOW_ERROR_NOTIFICATION",

  // Popup Events
  SHOW_RECENT_POPUP = "SHOW_RECENT_POPUP",
  RECENT_LOAD_PAGE = "RECENT_LOAD_PAGE",
  RECENT_ROW_CLICKED = "RECENT_ROW_CLICKED",
  SHOW_ROUND_DETAIL = "SHOW_ROUND_DETAIL",
  ROUND_DETAIL_OPENED = "ROUND_DETAIL_OPENED",
  ROUND_DETAIL_CLOSED = "ROUND_DETAIL_CLOSED",
  SHOW_INFO_POPUP = "SHOW_INFO_POPUP",
  SHOW_AUTOPLAY_POPUP = "SHOW_AUTOPLAY_POPUP",

  // Autoplay Events
  AUTOPLAY_STARTED = "AUTOPLAY_STARTED",
  AUTOPLAY_STOPPED = "AUTOPLAY_STOPPED",
  AUTOPLAY_ROUND_COMPLETE = "AUTOPLAY_ROUND_COMPLETE",
  AUTOPLAY_CONFIG_CHANGED = "AUTOPLAY_CONFIG_CHANGED",

  // UI Events
  UI_DIFFICULTY_CHANGED = "UI_DIFFICULTY_CHANGED",
  UI_BET_AMOUNT_CHANGED = "UI_BET_AMOUNT_CHANGED",
  UI_START_CLICKED = "UI_START_CLICKED",
  UI_JUMP_CLICKED = "UI_JUMP_CLICKED",
  UI_CASHOUT_CLICKED = "UI_CASHOUT_CLICKED",
  UI_TILE_CLICKED = "UI_TILE_CLICKED",
  UI_BUTTON_CLICKED = "UI_BUTTON_CLICKED",

  // State Update Events (for UI/Visual updates)
  STATE_UPDATED = "STATE_UPDATED",
  BALANCE_UPDATED = "BALANCE_UPDATED",
  MULTIPLIER_UPDATED = "MULTIPLIER_UPDATED",

  // Game Object Events
  TILE_REVEALED = "TILE_REVEALED",
  PLAYER_JUMP_START = "PLAYER_JUMP_START",
  PLAYER_JUMP_END = "PLAYER_JUMP_END",
  CAMERA_MOVED = "CAMERA_MOVED",

  // Scene Events
  SCENE_GENERATED = "SCENE_GENERATED",
  SCENE_CLEARED = "SCENE_CLEARED",
  SHOW_CRASH_POINT = "SHOW_CRASH_POINT",

  // Audio Events
  AUDIO_PLAY_SFX = "AUDIO_PLAY_SFX",
  AUDIO_PLAY_BGM = "AUDIO_PLAY_BGM",
  AUDIO_STOP_BGM = "AUDIO_STOP_BGM",
  AUDIO_SET_BGM_VOLUME = "AUDIO_SET_BGM_VOLUME",
  AUDIO_SET_SFX_VOLUME = "AUDIO_SET_SFX_VOLUME",
  AUDIO_TOGGLE_BGM_MUTE = "AUDIO_TOGGLE_BGM_MUTE",
  AUDIO_TOGGLE_SFX_MUTE = "AUDIO_TOGGLE_SFX_MUTE",
  AUDIO_BGM_MUTE_CHANGED = "AUDIO_BGM_MUTE_CHANGED",
  AUDIO_SFX_MUTE_CHANGED = "AUDIO_SFX_MUTE_CHANGED",

  // Game Speed Events
  GAME_SPEED_CHANGED = "GAME_SPEED_CHANGED",
  UI_SPEED_FAST_CLICKED = "UI_SPEED_FAST_CLICKED",
  UI_SPEED_NORMAL_CLICKED = "UI_SPEED_NORMAL_CLICKED",
}
